[package]
name = "nes_to_xinput"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
serialport = "4.2.0"
vigem-client = "0.1.4"
